In [6]:
import numpy as np
from PIL import Image

In [2]:
a =  np.random.randint(1,100,(4,2))
b =  np.random.randint(1,50,(4,2))


In [3]:
a

array([[60, 98],
       [ 4, 41],
       [84, 36],
       [98, 95]])

In [4]:
b

array([[41,  5],
       [15, 35],
       [14, 18],
       [36, 18]])

In [5]:
a+b

array([[101, 103],
       [ 19,  76],
       [ 98,  54],
       [134, 113]])