In [1]:
import numpy as np

In [2]:
it = [10,20,30,40,50]

In [3]:
n = np.array(it)

In [4]:
type(n)

numpy.ndarray

In [5]:
n

array([10, 20, 30, 40, 50])

In [6]:
d = {"a": "apple", "b":"banana","w": "Watermelon","m":"muskmelon"}

In [7]:
np.array(d)

array({'a': 'apple', 'b': 'banana', 'w': 'Watermelon', 'm': 'muskmelon'},
      dtype=object)

In [8]:
d2 = np.array([[1,2,3],[3,4,6],[6,5,8]])
d2

array([[1, 2, 3],
       [3, 4, 6],
       [6, 5, 8]])

In [9]:
y = np.array([1,2,3,"45"])

In [10]:
y

array(['1', '2', '3', '45'], dtype='<U11')

In [11]:
n.shape

(5,)

In [12]:

d2.shape

(3, 3)

In [13]:
d2.size


9

In [14]:
n.size

5

In [15]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(7,40,5)

array([ 7, 12, 17, 22, 27, 32, 37])

In [17]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
a = np.arange(40)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [19]:
a.reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [20]:
a[0]=100
a[1]=101
a[6]=103

In [21]:
a

array([100, 101,   2,   3,   4,   5, 103,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

In [22]:
a.reshape(8,5)

array([[100, 101,   2,   3,   4],
       [  5, 103,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39]])