In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.7.0'

In [3]:
a = tf.constant(10)
b = tf.constant(20)

In [4]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [5]:
tf.executing_eagerly()

True

In [6]:
tf.multiply(a,b).numpy()

200

In [7]:
a_mat = tf.constant([[1,2],[5,6]])
b_mat = tf.constant([[3,4],[6,7]])

In [8]:
tf.matmul(a_mat,b_mat)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 18],
       [51, 62]])>